name: envo_safe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  lottie: ^1.2.2
  intl: ^0.17.0
  image_picker: ^0.8.5
  image_cropper: ^2.0.0
  flutter_facebook_auth: ^4.3.0
  dio: ^4.0.6
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.5
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  razorpay_flutter: ^1.3.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0


dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/lottie/

